version: "3"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /opt/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no" # because the exit code(s) are wrong

  adguardhome:
    container_name: adguardhome
    restart: unless-stopped
    image: adguard/adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./adguard-work:/opt/adguardhome/work
      - ./adguard-conf:/opt/adguardhome/conf
    networks:
      macvlan:
        ipv4_address: 192.168.50.254 # this IP will show as a device on your router
      vlan_bridge:
        ipv4_address: 192.168.10.254 # Pick same last numbers as macvlan and use "vlan bridge subnet" (10)

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8123"]
      interval: 30s
      timeout: 10s
      retries: 6
